add ProbAI school, Finland
sshkhr/awesome-mlss pull request #100
Opened 2022-03-09 17:47 UTC by abonte

2022-03-10 03:50 UTC, sshkhr requested changes
Please make sure that the summer school is placed at its chronological position by date. Thank you

2022-03-10 07:09 UTC, abonte commented
Sorry, it's in reverse chronogical order, isn't correct? thank you

2022-03-11 07:45 UTC, sshkhr approved these changes

2022-03-11 07:45 UTC, sshkhr commented
My apologies! I misread the application deadline as the school dates

2022-03-11 07:45 UTC, merged