Add DL4NLP Spain summer school
sshkhr/awesome-mlss pull request #108
Opened 2022-04-26 13:13 UTC by vivianamarquez

Adding: https://ixa2.si.ehu.eus/deep_learning_seminar/

2022-05-12 17:35 UTC, sshkhr requested changes
Please make sure that the school is placed in the correct chronological order based on date of the event

2022-05-24 03:11 UTC, vivianamarquez commented
Updated the MR to reflect correct chronological order

2022-06-03 23:06 UTC, sshkhr approved these changes

2022-06-03 23:06 UTC, merged

2022-06-03 23:06 UTC, sshkhr commented
Thanks a lot!